# This is a basic workflow to help you get started with Actions

name: Pull request checks 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        matlabversion: [R2021a]
    uses: ./.github/workflows/run-tests.yml
    with:
      matlab: ${{matrix.matlabversion}}
  
  pr-status:
    if: always()
    needs:
    - run-tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Check complete!"
