# This is a basic workflow to help you get started with Actions

name: make-docs

# Controls when the workflow will run
on:
  push:
  workflow_dispatch:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  make-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
