name: miss_hit

on:
  workflow_dispatch:
  
  # push:
  #   # branches:
  # pull_request:

jobs:
  miss-hit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # submodules: true
        fetch-depth: 1

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip3 install miss_hit

    - name: MISS_HIT metric and lint
      run: |
        mh_metric --ci && mh_lint

    - name: MISS_HIT Code style
      run: |
        mh_style
