# This is a basic workflow to help you get started with Actions

name: Pull request status checks

# Controls when the workflow will run
on:
  # We want to run this workflow on all pull requests
  pull_request:

  # Also automated to run for all pushes to the default branch to ensure we have up-to-date results
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  contents: read

jobs:
#   build:
#   docs:
#   linters:
#   package-linters:
  tests:
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        matlabversion: [latest, R2021a]
    uses: ./.github/workflows/run-tests.yml
    with:
      runner: ${{ matrix.runner }}
      matlab: ${{ matrix.matlabversion }}

  coverage-report:
    needs: 
      - tests
    if: needs.pre-job.outputs.should-skip != 'true'
    uses: ./.github/workflows/coverage-report.yml
    with:
      matlab: latest
      runner: ubuntu-latest
      # Using a repository variable for this means only admins can adjust thresholds
      thresholds: ${{ vars.COVERAGE_THRESHOLDS }}

  comment-ratio:
    uses: ./.github/workflows/run-tests.yml
    with:
      failure_threshold: 0.25
  
  pull-request-check:
    needs:
    - tests
    - coverage-report
    - comment-ratio
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        # allowed-failures: docs, linters
        # allowed-skips:
        jobs: ${{ toJSON(needs) }}
