# This is a basic workflow to help you get started with Actions

name: Pull request status checks

# Controls when the workflow will run
on:
  # We want to run this workflow on all pull requests
  pull_request:

  # Also automated to run for all pushes to the default branch to ensure we have up-to-date results
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
#   build:
#   docs:
#   linters:
#   package-linters:
  tests:
    strategy:
      matrix:
        matlabversion: [R2021a, latest]
        # Matlab action *does not support toolboxes* on windows in v1
        # Exclude MacOS because of it's limited support by both GitHub and Matlab
        runner: [ubuntu-latest]  #, windows-latest]
    uses: ./.github/workflows/run-tests.yml
    with:
      matlab: ${{matrix.matlabversion}}
      runner: ${{matrix.runner}}

  coverage-report:
    if: always()
    needs: 
    - tests
    runs-on: ubuntu-latest
    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        name: code-coverage_R2021a-ubuntu-latest
        # pattern: "*_coverage.xml"
        merge-multiple: true
        path: test
        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: test/*_coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: false
        output: both
        thresholds: '60 90'
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
  
  pull-request-check:
    if: always()
    needs:
    - tests
    - coverage-report
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        # allowed-failures: docs, linters
        # allowed-skips:
        jobs: ${{ toJSON(needs) }}
