# This is a basic workflow to help you get started with Actions

name: Pull request status checks

# Controls when the workflow will run
on:
  # We want to run this workflow on all pull requests
  pull_request:

  # Also automated to run for all pushes to the default branch to ensure we have up-to-date results
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  contents: read

jobs:
  pre-job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should-skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: 'true'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '[".github/**"]'  # '["**/README.md", "**/docs/**"]'
          # do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
#   build:
#   docs:
#   linters:
#   package-linters:
  tests:
    needs: pre-job
    if: needs.pre-job.outputs.should-skip != 'true'
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest]
        matlabversion: [latest, R2021a]
    uses: ./.github/workflows/run-tests.yml
    with:
      runner: ${{ matrix.runner }}
      matlab: ${{ matrix.matlabversion }}

  coverage-report:
    needs: 
      - tests
      - pre-job
    if: needs.pre-job.outputs.should-skip != 'true'
    uses: ./.github/workflows/coverage-report.yml
    with:
      matlab: latest
      runner: ubuntu-latest
      # Using a repository variable for this means only admins can adjust thresholds
      thresholds: ${{ vars.COVERAGE_THRESHOLDS }}
  
  pull-request-check:
    if: always()
    needs:
    - tests
    - coverage-report
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        # allowed-failures: docs, linters
        # allowed-skips:
        jobs: ${{ toJSON(needs) }}
