# This is a basic workflow to help you get started with Actions

name: Pull request status checks

# Controls when the workflow will run
on:
  # We want to run this workflow on all pull requests
  # Also automated to run for all pushes to the default branch to ensure we have up-to-date results
  pull_request:
  push:
    branches: [ $default-branch ]
  
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      matrix:
        matlabversion: [R2021a, latest]
        # Matlab action *does not support toolboxes* on windows in v1
        # Exclude MacOS because of it's limited support by both GitHub and Matlab
        runner: [ubuntu-latest, windows-latest]
    uses: ./.github/workflows/run-tests.yml
    with:
      matlab: ${{matrix.matlabversion}}
      runner: ${{matrix.runner}}
  
  pull-request-status:
    if: always()
    needs:
    - run-tests
    runs-on: ubuntu-latest
    steps:
    - run: echo "Check complete!"
